### ISSUE TITLE
const array::operator[] is accessing non const members

### ISSUE THREAD

**Issue by mzanetti** [muwerk/ustd#16]
Using the const array::operator[] fails to build as it accesses non const method `resize()` as well as writing to member variable size which won't work:

https://github.com/muwerk/ustd/blob/master/ustd_array.h#L333

Looks like a copy/paste mistake from the non const version below.

**Comment by domschl** [comment]
The design decisions behind this where:
- for embedded systems, a read should never crash (with that patch, it would crash, since there are no more boundary checks
- Read (as write) can resize the array, depending on if initialization of the array allows dynamic growth.
I am no longer sure, if that was a good decision.

Can you show me a short code snippet that doesn't compile and illustrates your use-case?

**Comment by domschl** [comment]
You're basically right. Modifying the array on read was simply a bad design decision.
Since that's a breaking change I've to do some testing to see if that triggers some bugs in dependent projects of muwerk.
